<div class="jumbotron">
    <h1><span class="zf-green">Delete usuario</span></h1>
    <p>
        Confirm deletion of usuario with id: "<?= $usuario->getId() ?>"
    </p>
    <form action="<?= $this->url('usuarios', ['action' => 'delete', 'id' => $id]) ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $usuario->getId() ?>" />
            <input type="submit" class="btn btn-danger" name="del" value="Delete" />
            <input type="submit" class="btn btn-success" name="del" value="Cancel" />
        </div>
    </form>
</div>